#!/usr/bin/env python3
"""Enforce UTF-8 BOM - auto-generated by pre-commit-template."""
import sys

def main():
    missing = []
    unreadable = []
    for filepath in sys.argv[1:]:
        try:
            with open(filepath, 'rb') as f:
                if f.read(3) != b'\xef\xbb\xbf':
                    missing.append(filepath)
        except OSError as e:
            # Fail closed: a gate hook must not treat files it cannot read
            # as BOM-compliant (an unreadable staged file fails the run).
            unreadable.append((filepath, str(e)))
    for filepath, err in unreadable:
        print(f"[ERROR] Cannot read {filepath}: {err}", file=sys.stderr)
    if missing:
        print("[ERROR] Missing UTF-8 BOM signature in:", file=sys.stderr)
        for path in missing:
            print(f"  - {path}", file=sys.stderr)
    if missing or unreadable:
        sys.exit(1)
    sys.exit(0)

if __name__ == "__main__":
    main()
