// Generated by backend/cmd/contractgen. Do not edit.
import Foundation

enum BackendProtocolContract {
    static let protocolVersion = 12
    static let shutdownGraceSeconds: TimeInterval = 5
}

enum ApplicationIdentity {
    static let name = "Codex Tweaks Companion"
    static let bundleIdentifier = "io.github.aloysk.codexcompanion"
    static let environmentPrefix = "CODEX_COMPANION_"
    static let updatesEnabled = false
}

enum PresentationTextKey: String, CaseIterable, Sendable {
    case appBackendDateMalformed = "app.backendDateMalformed"
    case appBackendMalformed = "app.backendMalformed"
    case appBackendMissing = "app.backendMissing"
    case appBackendNotRunning = "app.backendNotRunning"
    case appBackendRequestCreateFailed = "app.backendRequestCreateFailed"
    case appBackendRequestFailed = "app.backendRequestFailed"
    case appBackendShutdownIncomplete = "app.backendShutdownIncomplete"
    case appBackendTerminated = "app.backendTerminated"
    case appBackendTimedOut = "app.backendTimedOut"
    case appName = "app.name"
    case appProtocolMismatch = "app.protocolMismatch"
    case appearanceApply = "appearance.apply"
    case appearanceBackground = "appearance.background"
    case appearanceBackgroundLocalImage = "appearance.background.localImage"
    case appearanceBackgroundOff = "appearance.background.off"
    case appearanceBackgroundSolid = "appearance.background.solid"
    case appearanceBusy = "appearance.busy"
    case appearanceCancelPreview = "appearance.cancelPreview"
    case appearanceChooseImage = "appearance.chooseImage"
    case appearanceErrorAmbiguousTarget = "appearance.error.ambiguousTarget"
    case appearanceErrorAssetUnavailable = "appearance.error.assetUnavailable"
    case appearanceErrorCancelled = "appearance.error.cancelled"
    case appearanceErrorImageDimensions = "appearance.error.imageDimensions"
    case appearanceErrorImageRead = "appearance.error.imageRead"
    case appearanceErrorImageSize = "appearance.error.imageSize"
    case appearanceErrorImageType = "appearance.error.imageType"
    case appearanceErrorImageWrite = "appearance.error.imageWrite"
    case appearanceErrorInvalidSettings = "appearance.error.invalidSettings"
    case appearanceErrorPersistence = "appearance.error.persistence"
    case appearanceErrorRenderer = "appearance.error.renderer"
    case appearanceErrorUnavailable = "appearance.error.unavailable"
    case appearanceErrorUnsupportedLayout = "appearance.error.unsupportedLayout"
    case appearanceImage = "appearance.image"
    case appearanceImageImported = "appearance.imageImported"
    case appearanceImageLimits = "appearance.imageLimits"
    case appearanceImageNone = "appearance.imageNone"
    case appearanceImageSelected = "appearance.imageSelected"
    case appearanceLayout = "appearance.layout"
    case appearanceLayoutComfortable = "appearance.layout.comfortable"
    case appearanceLayoutCompact = "appearance.layout.compact"
    case appearanceLayoutNative = "appearance.layout.native"
    case appearanceLayoutUnavailable = "appearance.layoutUnavailable"
    case appearanceLocalDraft = "appearance.localDraft"
    case appearanceOpacityValue = "appearance.opacityValue"
    case appearanceOverlayOpacity = "appearance.overlayOpacity"
    case appearancePreview = "appearance.preview"
    case appearancePreviewOnly = "appearance.previewOnly"
    case appearanceRequestFailed = "appearance.requestFailed"
    case appearanceRestoreNative = "appearance.restoreNative"
    case appearanceSavedSettings = "appearance.savedSettings"
    case appearanceSolidColor = "appearance.solidColor"
    case appearanceStatusApplied = "appearance.status.applied"
    case appearanceStatusNative = "appearance.status.native"
    case appearanceStatusPreview = "appearance.status.preview"
    case appearanceStatusRecoveryPending = "appearance.status.recoveryPending"
    case appearanceStatusUnavailable = "appearance.status.unavailable"
    case appearanceStatusUnsaved = "appearance.status.unsaved"
    case appearanceStatusUnsupported = "appearance.status.unsupported"
    case appearanceSubtitle = "appearance.subtitle"
    case appearanceTarget = "appearance.target"
    case appearanceTargetUnconfirmed = "appearance.targetUnconfirmed"
    case appearanceTheme = "appearance.theme"
    case appearanceThemeDark = "appearance.theme.dark"
    case appearanceThemeMint = "appearance.theme.mint"
    case appearanceThemeNative = "appearance.theme.native"
    case appearanceTitle = "appearance.title"
    case appearanceUnsupportedOption = "appearance.unsupportedOption"
    case commonCancel = "common.cancel"
    case commonClose = "common.close"
    case commonConfirm = "common.confirm"
    case commonCopy = "common.copy"
    case commonOk = "common.ok"
    case commonOpen = "common.open"
    case dialogRestartCodexUIMessage = "dialog.restartCodexUIMessage"
    case dialogRestartCodexUITitle = "dialog.restartCodexUITitle"
    case dialogRestartMessage = "dialog.restartMessage"
    case dialogRestartTitle = "dialog.restartTitle"
    case languageAuto = "language.auto"
    case languageEffective = "language.effective"
    case languageEnglish = "language.english"
    case languageJapanese = "language.japanese"
    case languageKorean = "language.korean"
    case languageSelection = "language.selection"
    case languageSimplifiedChinese = "language.simplifiedChinese"
    case languageSubtitle = "language.subtitle"
    case languageTitle = "language.title"
    case languageTraditionalChinese = "language.traditionalChinese"
    case logsClear = "logs.clear"
    case logsClearFailed = "logs.clearFailed"
    case logsClearMessage = "logs.clearMessage"
    case logsClearTitle = "logs.clearTitle"
    case logsEmpty = "logs.empty"
    case logsOpenFile = "logs.openFile"
    case logsRefresh = "logs.refresh"
    case logsSubtitle = "logs.subtitle"
    case logsTitle = "logs.title"
    case menuQuit = "menu.quit"
    case menuShow = "menu.show"
    case navAppearance = "nav.appearance"
    case navLogs = "nav.logs"
    case navOverview = "nav.overview"
    case navPackages = "nav.packages"
    case navUpdates = "nav.updates"
    case overviewAiAuthoring = "overview.aiAuthoring"
    case overviewAppPagesOnly = "overview.appPagesOnly"
    case overviewCdpEndpoint = "overview.cdpEndpoint"
    case overviewConnectedDetail = "overview.connectedDetail"
    case overviewConnectingDetail = "overview.connectingDetail"
    case overviewConnection = "overview.connection"
    case overviewControl = "overview.control"
    case overviewCopied = "overview.copied"
    case overviewCopy = "overview.copy"
    case overviewCopyHint = "overview.copyHint"
    case overviewCopySkill = "overview.copySkill"
    case overviewCopySkillDetail = "overview.copySkillDetail"
    case overviewDisableGPUAcceleration = "overview.disableGPUAcceleration"
    case overviewDisableGPUAccelerationDetail = "overview.disableGPUAccelerationDetail"
    case overviewDisabledDetail = "overview.disabledDetail"
    case overviewEnable = "overview.enable"
    case overviewEnableDetail = "overview.enableDetail"
    case overviewErrorDetail = "overview.errorDetail"
    case overviewHideDockIcon = "overview.hideDockIcon"
    case overviewHideDockIconDetail = "overview.hideDockIconDetail"
    case overviewHideMenuBarIcon = "overview.hideMenuBarIcon"
    case overviewHideMenuBarIconDetail = "overview.hideMenuBarIconDetail"
    case overviewInjectionScope = "overview.injectionScope"
    case overviewLoadOrder = "overview.loadOrder"
    case overviewLoadOrderDetail = "overview.loadOrderDetail"
    case overviewManagePackages = "overview.managePackages"
    case overviewOpenCodex = "overview.openCodex"
    case overviewOpenCodexDetail = "overview.openCodexDetail"
    case overviewOpenPackagesDirectory = "overview.openPackagesDirectory"
    case overviewRefreshEveryTwoSeconds = "overview.refreshEveryTwoSeconds"
    case overviewRefreshPolicy = "overview.refreshPolicy"
    case overviewReinject = "overview.reinject"
    case overviewResources = "overview.resources"
    case overviewRestartAndConnect = "overview.restartAndConnect"
    case overviewRestartCodexUI = "overview.restartCodexUI"
    case overviewRestartCodexUIDetail = "overview.restartCodexUIDetail"
    case overviewRestartDetail = "overview.restartDetail"
    case overviewSubtitle = "overview.subtitle"
    case overviewTitle = "overview.title"
    case overviewViewLogs = "overview.viewLogs"
    case packagesActiveVersion = "packages.activeVersion"
    case packagesBuild = "packages.build"
    case packagesBuilding = "packages.building"
    case packagesCannotBuild = "packages.cannotBuild"
    case packagesCheckRemoteUpdates = "packages.checkRemoteUpdates"
    case packagesCheckingRemote = "packages.checkingRemote"
    case packagesChooseDirectory = "packages.chooseDirectory"
    case packagesChooseZip = "packages.chooseZip"
    case packagesClearError = "packages.clearError"
    case packagesClearMessage = "packages.clearMessage"
    case packagesClearSearch = "packages.clearSearch"
    case packagesCollapsed = "packages.collapsed"
    case packagesDelete = "packages.delete"
    case packagesDeleteConfirm = "packages.deleteConfirm"
    case packagesDeleteFailed = "packages.deleteFailed"
    case packagesDeleteHelp = "packages.deleteHelp"
    case packagesDeleteMessage = "packages.deleteMessage"
    case packagesDeleteSuccess = "packages.deleteSuccess"
    case packagesDeleteTitle = "packages.deleteTitle"
    case packagesDependencyConstraint = "packages.dependencyConstraint"
    case packagesDependencyInstalledSource = "packages.dependencyInstalledSource"
    case packagesDependencyNoGitSource = "packages.dependencyNoGitSource"
    case packagesDependencyOrderFirst = "packages.dependencyOrderFirst"
    case packagesDependencyOriginInstallable = "packages.dependencyOrigin.installable"
    case packagesDependencyOriginLocal = "packages.dependencyOrigin.local"
    case packagesDependencyOriginLocalOnly = "packages.dependencyOrigin.localOnly"
    case packagesDependencyOriginManaged = "packages.dependencyOrigin.managed"
    case packagesDependencySelector = "packages.dependencySelector"
    case packagesDependencyStateBlocked = "packages.dependencyState.blocked"
    case packagesDependencyStateCycle = "packages.dependencyState.cycle"
    case packagesDependencyStateDisabled = "packages.dependencyState.disabled"
    case packagesDependencyStateDisabledVersion = "packages.dependencyState.disabledVersion"
    case packagesDependencyStateInvalidRequirement = "packages.dependencyState.invalidRequirement"
    case packagesDependencyStateMissingInstallable = "packages.dependencyState.missingInstallable"
    case packagesDependencyStateMissingLocal = "packages.dependencyState.missingLocal"
    case packagesDependencyStateNotBuilt = "packages.dependencyState.notBuilt"
    case packagesDependencyStateNotBuiltVersion = "packages.dependencyState.notBuiltVersion"
    case packagesDependencyStateSatisfied = "packages.dependencyState.satisfied"
    case packagesDependencyStateSatisfiedVersion = "packages.dependencyState.satisfiedVersion"
    case packagesDependencyStateSelfReference = "packages.dependencyState.selfReference"
    case packagesDependencyStateSourceConflict = "packages.dependencyState.sourceConflict"
    case packagesDependencyStateVersionMismatch = "packages.dependencyState.versionMismatch"
    case packagesDependencySummaryCritical = "packages.dependencySummaryCritical"
    case packagesDependencySummaryOK = "packages.dependencySummaryOK"
    case packagesDependencySummaryPending = "packages.dependencySummaryPending"
    case packagesDetailActiveBuildError = "packages.detail.activeBuildError"
    case packagesDetailCompilerUpdate = "packages.detail.compilerUpdate"
    case packagesDetailDeleting = "packages.detail.deleting"
    case packagesDetailDependencyIssues = "packages.detail.dependencyIssues"
    case packagesDetailDependencyUpdate = "packages.detail.dependencyUpdate"
    case packagesDetailExporting = "packages.detail.exporting"
    case packagesDetailLastBuilt = "packages.detail.lastBuilt"
    case packagesDetailNodeAuthorizationRequired = "packages.detail.nodeAuthorizationRequired"
    case packagesDetailPinnedChanged = "packages.detail.pinnedChanged"
    case packagesDetailRemoteAvailable = "packages.detail.remoteAvailable"
    case packagesDetailSourceChanged = "packages.detail.sourceChanged"
    case packagesDetailVersionUpdate = "packages.detail.versionUpdate"
    case packagesDeveloperAllowUnknownNode = "packages.developerAllowUnknownNode"
    case packagesDeveloperAllowUnknownNodeDetail = "packages.developerAllowUnknownNodeDetail"
    case packagesDeveloperMode = "packages.developerMode"
    case packagesDeveloperModeDetail = "packages.developerModeDetail"
    case packagesEmptyDetail = "packages.emptyDetail"
    case packagesEmptyTitle = "packages.emptyTitle"
    case packagesEnableDependencies = "packages.enableDependencies"
    case packagesEnablePackage = "packages.enablePackage"
    case packagesEnabledSummary = "packages.enabledSummary"
    case packagesExpanded = "packages.expanded"
    case packagesExportFailed = "packages.exportFailed"
    case packagesExportSuccess = "packages.exportSuccess"
    case packagesExportZip = "packages.exportZip"
    case packagesExportZipHelp = "packages.exportZipHelp"
    case packagesExporting = "packages.exporting"
    case packagesFilter = "packages.filter"
    case packagesFilterAll = "packages.filter.all"
    case packagesFilterDisabled = "packages.filter.disabled"
    case packagesFilterEnabled = "packages.filter.enabled"
    case packagesFilterError = "packages.filter.error"
    case packagesFilterPending = "packages.filter.pending"
    case packagesGitAvailable = "packages.gitAvailable"
    case packagesGitChecking = "packages.gitChecking"
    case packagesGitMissing = "packages.gitMissing"
    case packagesInstallAndBuild = "packages.installAndBuild"
    case packagesInstallDependencies = "packages.installDependencies"
    case packagesInstallFailed = "packages.installFailed"
    case packagesInstallLocal = "packages.installLocal"
    case packagesInstallLocalHelp = "packages.installLocalHelp"
    case packagesInstallRemote = "packages.installRemote"
    case packagesInstallSuccess = "packages.installSuccess"
    case packagesInstalling = "packages.installing"
    case packagesInstallingLocal = "packages.installingLocal"
    case packagesLoadOrder = "packages.loadOrder"
    case packagesLoadOrderDetail = "packages.loadOrderDetail"
    case packagesNoDescription = "packages.noDescription"
    case packagesNoMatchDetail = "packages.noMatchDetail"
    case packagesNoMatchTitle = "packages.noMatchTitle"
    case packagesNodeAuthorizationAllow = "packages.nodeAuthorizationAllow"
    case packagesNodeAuthorizationCancel = "packages.nodeAuthorizationCancel"
    case packagesNodeAuthorizationReason = "packages.nodeAuthorizationReason"
    case packagesNodeAuthorizationTitle = "packages.nodeAuthorizationTitle"
    case packagesNodeAuthorizationWarning = "packages.nodeAuthorizationWarning"
    case packagesNodeAutomaticWarning = "packages.nodeAutomaticWarning"
    case packagesNodeAutomaticWarningAllow = "packages.nodeAutomaticWarningAllow"
    case packagesNodeAutomaticWarningTitle = "packages.nodeAutomaticWarningTitle"
    case packagesNodeAvailable = "packages.nodeAvailable"
    case packagesNodeChecking = "packages.nodeChecking"
    case packagesNodeMissing = "packages.nodeMissing"
    case packagesNotBuiltDetail = "packages.notBuiltDetail"
    case packagesOpenDirectory = "packages.openDirectory"
    case packagesOpenProjectPage = "packages.openProjectPage"
    case packagesPackageCountSuffix = "packages.packageCountSuffix"
    case packagesPriority = "packages.priority"
    case packagesPriorityActual = "packages.priorityActual"
    case packagesPriorityAfter = "packages.priorityAfter"
    case packagesPriorityBefore = "packages.priorityBefore"
    case packagesRebuild = "packages.rebuild"
    case packagesRescan = "packages.rescan"
    case packagesResetPriority = "packages.resetPriority"
    case packagesSearchPlaceholder = "packages.searchPlaceholder"
    case packagesSourceVersion = "packages.sourceVersion"
    case packagesStatusActive = "packages.status.active"
    case packagesStatusBuildFailed = "packages.status.buildFailed"
    case packagesStatusBuilding = "packages.status.building"
    case packagesStatusCompilerChanged = "packages.status.compilerChanged"
    case packagesStatusDeleting = "packages.status.deleting"
    case packagesStatusDependency = "packages.status.dependency"
    case packagesStatusDependencyBlocked = "packages.status.dependencyBlocked"
    case packagesStatusDependencyChanged = "packages.status.dependencyChanged"
    case packagesStatusDisabled = "packages.status.disabled"
    case packagesStatusExporting = "packages.status.exporting"
    case packagesStatusInstallingRemote = "packages.status.installingRemote"
    case packagesStatusInvalid = "packages.status.invalid"
    case packagesStatusNewVersion = "packages.status.newVersion"
    case packagesStatusNodeAuthorizationRequired = "packages.status.nodeAuthorizationRequired"
    case packagesStatusNotBuilt = "packages.status.notBuilt"
    case packagesStatusPayloadFailed = "packages.status.payloadFailed"
    case packagesStatusPending = "packages.status.pending"
    case packagesStatusPinnedChanged = "packages.status.pinnedChanged"
    case packagesStatusRemoteFailed = "packages.status.remoteFailed"
    case packagesStatusRemoteUpdate = "packages.status.remoteUpdate"
    case packagesStatusRuntimeFailed = "packages.status.runtimeFailed"
    case packagesStatusSourceChanged = "packages.status.sourceChanged"
    case packagesStatusUnavailable = "packages.status.unavailable"
    case packagesSubtitle = "packages.subtitle"
    case packagesSyncAndBuild = "packages.syncAndBuild"
    case packagesTitle = "packages.title"
    case packagesUpdateAndBuild = "packages.updateAndBuild"
    case packagesUpdateBuild = "packages.updateBuild"
    case packagesUpdateToVersion = "packages.updateToVersion"
    case packagesUserPriority = "packages.userPriority"
    case packagesZipFileType = "packages.zipFileType"
    case remoteClose = "remote.close"
    case remoteInstall = "remote.install"
    case remoteRepository = "remote.repository"
    case remoteRepositoryPlaceholder = "remote.repositoryPlaceholder"
    case remoteSelector = "remote.selector"
    case remoteSubtitle = "remote.subtitle"
    case remoteTitle = "remote.title"
    case remoteValidationDetail = "remote.validationDetail"
    case runtimeEnhancementUnsupported = "runtime.enhancementUnsupported"
    case runtimeEnhancementUnsupportedTitle = "runtime.enhancementUnsupportedTitle"
    case selectorBranch = "selector.branch"
    case selectorBranchDefault = "selector.branchDefault"
    case selectorBranchValue = "selector.branchValue"
    case selectorCommit = "selector.commit"
    case selectorCommitValue = "selector.commitValue"
    case selectorDefaultBranch = "selector.defaultBranch"
    case selectorGithubLatestRelease = "selector.githubLatestRelease"
    case selectorGithubRelease = "selector.githubRelease"
    case selectorGithubReleaseValue = "selector.githubReleaseValue"
    case selectorLatestSemverTag = "selector.latestSemverTag"
    case selectorTag = "selector.tag"
    case selectorTagValue = "selector.tagValue"
    case statusCodexNotRunningDetail = "status.codexNotRunning.detail"
    case statusCodexNotRunningTitle = "status.codexNotRunning.title"
    case statusConnectedMany = "status.connected.many"
    case statusConnectedOne = "status.connected.one"
    case statusDisabledTitle = "status.disabled.title"
    case statusErrorTitle = "status.error.title"
    case statusLaunchingCodexTitle = "status.launchingCodex.title"
    case statusRecoveryPendingDetail = "status.recoveryPending.detail"
    case statusRecoveryPendingTitle = "status.recoveryPending.title"
    case statusRestartRequiredDetail = "status.restartRequired.detail"
    case statusRestartRequiredTitle = "status.restartRequired.title"
    case statusStartingTitle = "status.starting.title"
    case statusWaitingForCDPTitle = "status.waitingForCDP.title"
    case statusWaitingForPageDetail = "status.waitingForPage.detail"
    case statusWaitingForPageTitle = "status.waitingForPage.title"
    case updateApplyProgress = "update.applyProgress"
    case updateAutoCheck = "update.autoCheck"
    case updateAvailable = "update.available"
    case updateChannel = "update.channel"
    case updateChannelBeta = "update.channel.beta"
    case updateChannelBetaDetail = "update.channel.betaDetail"
    case updateChannelStable = "update.channel.stable"
    case updateChannelStableDetail = "update.channel.stableDetail"
    case updateCheck = "update.check"
    case updateCheckFailed = "update.checkFailed"
    case updateCheckFirst = "update.checkFirst"
    case updateChecking = "update.checking"
    case updateCurrent = "update.current"
    case updateCurrentVersion = "update.currentVersion"
    case updateDownload = "update.download"
    case updateDownloadProgress = "update.downloadProgress"
    case updateInstall = "update.install"
    case updateInstallFailed = "update.installFailed"
    case updateInstallingProgress = "update.installingProgress"
    case updateLastCheck = "update.lastCheck"
    case updateLater = "update.later"
    case updateLatestVersion = "update.latestVersion"
    case updateNetworkUnavailable = "update.networkUnavailable"
    case updateNever = "update.never"
    case updateNoRelease = "update.noRelease"
    case updateNoneAvailable = "update.noneAvailable"
    case updateNotConfigured = "update.notConfigured"
    case updateNotInstalled = "update.notInstalled"
    case updatePromptMessage = "update.promptMessage"
    case updateRepository = "update.repository"
    case updateRestoreReminder = "update.restoreReminder"
    case updateSkip = "update.skip"
    case updateSkipMessage = "update.skipMessage"
    case updateSkipped = "update.skipped"
    case updateSoftwareUpdate = "update.softwareUpdate"
    case updateSubtitle = "update.subtitle"
    case updateTitle = "update.title"
    case updateVersionBuild = "update.versionBuild"
    case updateViewRelease = "update.viewRelease"
}

struct BackendPresentationTokens: Codable, Equatable, Sendable {
    let windowMinWidth: Int
    let windowMinHeight: Int
    let windowDefaultWidth: Int
    let windowDefaultHeight: Int
    let navigationWidth: Int
    let contentMaxWidth: Int
    let pagePadding: Int
    let sectionSpacing: Int
    let cardPadding: Int
    let cardCornerRadius: Int
    let controlSpacing: Int
    let compactSpacing: Int
    let statusIconSize: Int
    let animationFastMS: Int
    let animationStandardMS: Int
    let accentColor: String
    let successColor: String
    let warningColor: String
    let dangerColor: String
}

struct BackendAvailableActions: Codable, Equatable, Sendable {
    let openCodex: Bool
    let restartCodex: Bool
    let restartCodexUI: Bool
    let reinject: Bool
    let openPackagesDirectory: Bool
    let openLogFile: Bool
    let openRepository: Bool
    let setEnabled: Bool
    let setDisableGPUAcceleration: Bool
    let setDeveloperMode: Bool
    let reloadPackages: Bool
    let installLocalPackage: Bool
    let installRemotePackage: Bool
    let checkNodeEnvironment: Bool
    let checkGitEnvironment: Bool
    let checkManagedPackageUpdates: Bool
    let refreshLog: Bool
    let clearLog: Bool
    let readAuthoringPrompt: Bool
    let checkAppUpdate: Bool
    let setUpdatePreferences: Bool
    let setLanguage: Bool
    let installAppUpdate: Bool
}

struct BackendStatusPresentation: Codable, Equatable, Sendable {
    let title: String
    let detail: String
    let tone: String
}

struct BackendPlatformPresentation: Codable, Equatable, Sendable {
    let operatingSystem: String
    let architecture: String
    let cdpEndpoint: String
    let repositoryURL: String
    let updateInstallStrategy: String
}

struct BackendPresentationContract: Codable, Equatable, Sendable {
    let version: Int
    let locale: String
    let languagePreference: String
    let languageOrder: [String]
    let languageOptions: [String: String]
    let text: [String: String]
    let tokens: BackendPresentationTokens
    let actions: BackendAvailableActions
    let status: BackendStatusPresentation
    let platform: BackendPlatformPresentation
}

struct BackendShutdownResult: Codable, Equatable, Sendable {
    let shutdown: Bool
}

struct BackendAppearanceSettings: Codable, Equatable, Sendable {
    let theme: String
    let readingLayout: String
    let backgroundMode: String
    let solidColor: String
    let imageAssetId: String?
    let overlayOpacity: Int
}

struct BackendAppearanceOption: Codable, Equatable, Sendable {
    let value: String
    let textKey: String
    let supported: Bool
}

struct BackendAppearanceOptions: Codable, Equatable, Sendable {
    let themes: [BackendAppearanceOption]
    let readingLayouts: [BackendAppearanceOption]
    let backgroundModes: [BackendAppearanceOption]
    let overlayMinimum: Int
    let overlayMaximum: Int
}

struct BackendAppearanceActions: Codable, Equatable, Sendable {
    let preview: Bool
    let apply: Bool
    let cancelPreview: Bool
    let restoreNative: Bool
    let importImage: Bool
}

struct BackendAppearanceSnapshot: Codable, Equatable, Sendable {
    let saved: BackendAppearanceSettings
    let preview: BackendAppearanceSettings?
    let status: String
    let statusTextKey: String
    let errorTextKey: String?
    let targetId: String?
    let revision: UInt64
    let actions: BackendAppearanceActions
    let options: BackendAppearanceOptions
}

struct BackendAppearanceImageResult: Codable, Equatable, Sendable {
    let assetId: String
    let width: Int
    let height: Int
    let format: String
}

enum GeneratedAppearanceDefaults {
    static let settings = BackendAppearanceSettings(theme: "native", readingLayout: "native", backgroundMode: "off", solidColor: "#DEF3E5", imageAssetId: nil, overlayOpacity: 88)
}

enum GeneratedPresentationDefaults {
    static let text: [PresentationTextKey: String] = [
        .appBackendDateMalformed: "Could not parse the date returned by the Go backend: {value}",
        .appBackendMalformed: "The Go backend returned an unreadable response.",
        .appBackendMissing: "The Go backend executable is missing from the app bundle.",
        .appBackendNotRunning: "The Go backend is not running.",
        .appBackendRequestCreateFailed: "Could not create the Go backend request.",
        .appBackendRequestFailed: "The Go backend request failed.",
        .appBackendShutdownIncomplete: "Page cleanup has not been confirmed. Companion will exit; save your work, normally exit the official Codex app, then reopen it from its official entry point.",
        .appBackendTerminated: "The Go backend exited with status {status}.",
        .appBackendTimedOut: "The Go backend response timed out.",
        .appName: "Codex Tweaks Companion",
        .appProtocolMismatch: "The Go backend protocol version does not match.",
        .appearanceApply: "Apply and save",
        .appearanceBackground: "Background",
        .appearanceBackgroundLocalImage: "Local image",
        .appearanceBackgroundOff: "Off",
        .appearanceBackgroundSolid: "Solid color",
        .appearanceBusy: "Working…",
        .appearanceCancelPreview: "Cancel preview",
        .appearanceChooseImage: "Choose image",
        .appearanceErrorAmbiguousTarget: "Multiple Codex windows were found. The target could not be confirmed.",
        .appearanceErrorAssetUnavailable: "The background image is unavailable. Choose it again.",
        .appearanceErrorCancelled: "The action was cancelled.",
        .appearanceErrorImageDimensions: "Neither side of the image may exceed 4096 pixels.",
        .appearanceErrorImageRead: "Could not read the image.",
        .appearanceErrorImageSize: "The image must be no larger than 5 MiB.",
        .appearanceErrorImageType: "Choose a static PNG, JPEG, or WebP image.",
        .appearanceErrorImageWrite: "Could not save the image.",
        .appearanceErrorInvalidSettings: "The appearance settings are invalid.",
        .appearanceErrorPersistence: "Saving failed. The current preview has not been saved.",
        .appearanceErrorRenderer: "Could not update Codex appearance.",
        .appearanceErrorUnavailable: "Codex appearance cannot be adjusted right now.",
        .appearanceErrorUnsupportedLayout: "This layout is currently unavailable.",
        .appearanceImage: "Image",
        .appearanceImageImported: "Imported {width}×{height} · {format}",
        .appearanceImageLimits: "Static PNG, JPEG, or WebP; up to 5 MiB and 4096 pixels per side.",
        .appearanceImageNone: "No image selected",
        .appearanceImageSelected: "Image selected",
        .appearanceLayout: "Layout",
        .appearanceLayoutComfortable: "Comfortable",
        .appearanceLayoutCompact: "Compact",
        .appearanceLayoutNative: "Native",
        .appearanceLayoutUnavailable: "Layout adjustments are currently unavailable.",
        .appearanceLocalDraft: "Draft not yet sent",
        .appearanceOpacityValue: "{value}%",
        .appearanceOverlayOpacity: "Background overlay opacity",
        .appearancePreview: "Preview",
        .appearancePreviewOnly: "Preview changes have not been saved.",
        .appearanceRequestFailed: "The action failed. Try again.",
        .appearanceRestoreNative: "Restore native appearance",
        .appearanceSavedSettings: "Current settings are saved.",
        .appearanceSolidColor: "Solid color",
        .appearanceStatusApplied: "Applied",
        .appearanceStatusNative: "Native appearance",
        .appearanceStatusPreview: "Previewing",
        .appearanceStatusRecoveryPending: "Recovery pending",
        .appearanceStatusUnavailable: "Unavailable",
        .appearanceStatusUnsaved: "Unsaved",
        .appearanceStatusUnsupported: "Unsupported",
        .appearanceSubtitle: "Customize the theme and background of the official Codex app.",
        .appearanceTarget: "Target: {target}",
        .appearanceTargetUnconfirmed: "Codex window not yet confirmed",
        .appearanceTheme: "Theme",
        .appearanceThemeDark: "Dark",
        .appearanceThemeMint: "Mint",
        .appearanceThemeNative: "Native",
        .appearanceTitle: "Appearance",
        .appearanceUnsupportedOption: "This option is currently unavailable.",
        .commonCancel: "Cancel",
        .commonClose: "Close",
        .commonConfirm: "Confirm",
        .commonCopy: "Copy",
        .commonOk: "OK",
        .commonOpen: "Open",
        .dialogRestartCodexUIMessage: "This reloads every connected Codex interface without quitting Codex. Unsubmitted input may be lost.",
        .dialogRestartCodexUITitle: "Restart the Codex interface?",
        .dialogRestartMessage: "Codex can enable CDP only when it starts. Codex Tweaks will restore injections automatically after the restart.",
        .dialogRestartTitle: "Restart Codex?",
        .languageAuto: "Automatic (System Language)",
        .languageEffective: "Current display language: {language}",
        .languageEnglish: "English",
        .languageJapanese: "日本語",
        .languageKorean: "한국어",
        .languageSelection: "Display language",
        .languageSimplifiedChinese: "简体中文",
        .languageSubtitle: "Follow your system's preferred language by default, or choose a display language just for Codex Tweaks.",
        .languageTitle: "Language",
        .languageTraditionalChinese: "繁體中文",
        .logsClear: "Clear logs",
        .logsClearFailed: "Could not clear logs",
        .logsClearMessage: "All existing entries in the log file will be permanently deleted. This action cannot be undone.",
        .logsClearTitle: "Clear all logs?",
        .logsEmpty: "No logs yet",
        .logsOpenFile: "Open log file",
        .logsRefresh: "Refresh",
        .logsSubtitle: "View recent startup, connection, and injection logs, or open the log file for the complete history.",
        .logsTitle: "Connection and injection logs",
        .menuQuit: "Quit Codex Tweaks",
        .menuShow: "Show Codex Tweaks",
        .navAppearance: "Appearance",
        .navLogs: "Logs",
        .navOverview: "Overview",
        .navPackages: "Packages",
        .navUpdates: "About & Updates",
        .overviewAiAuthoring: "Create with AI",
        .overviewAppPagesOnly: "Verified official Codex main page",
        .overviewCdpEndpoint: "CDP endpoint",
        .overviewConnectedDetail: "Compiled and enabled packages have been applied to Codex.",
        .overviewConnectingDetail: "Codex Tweaks is establishing a local connection.",
        .overviewConnection: "Connection",
        .overviewControl: "Controls",
        .overviewCopied: "Copied",
        .overviewCopy: "Copy Skill",
        .overviewCopyHint: "Paste it into Codex or another agent after copying",
        .overviewCopySkill: "Copy the Codex Tweaks package-development Skill",
        .overviewCopySkillDetail: "The copied content comes directly from the project's shared SKILL.md, so it always uses the same package protocol, dependencies, and validation rules. Add your specific request after pasting it.",
        .overviewDisableGPUAcceleration: "Disable Codex GPU acceleration",
        .overviewDisableGPUAccelerationDetail: "Off by default. Try enabling it only when Codex has graphics-rendering, transparent-window, or interface-compositing issues. It takes effect the next time Codex starts or restarts, switches to CPU software rendering, and may reduce graphics performance or increase CPU usage.",
        .overviewDisabledDetail: "Further injection is stopped. Page cleanup and debug listener state are verified separately; exit normally and reopen from the official entry point to close the listener.",
        .overviewEnable: "Enable interface enhancements",
        .overviewEnableDetail: "Stop further injection and verify cleanup. Failed cleanup remains pending and can be retried.",
        .overviewErrorDetail: "See the runtime logs for details.",
        .overviewHideDockIcon: "Hide Dock icon",
        .overviewHideDockIconDetail: "Also hides the app from the Command-Tab app switcher. Background injection continues after closing the window; reopen Codex Tweaks to restore it.",
        .overviewHideMenuBarIcon: "Hide menu bar icon",
        .overviewHideMenuBarIconDetail: "Injection continues while the icon is hidden. Reopen Codex Tweaks from Applications to restore the window.",
        .overviewInjectionScope: "Injection scope",
        .overviewLoadOrder: "Package load order",
        .overviewLoadOrderDetail: "Dependency topology first, then effective user priority from lowest to highest",
        .overviewManagePackages: "Manage packages",
        .overviewOpenCodex: "Open Codex",
        .overviewOpenCodexDetail: "The connection will be established automatically after Codex opens.",
        .overviewOpenPackagesDirectory: "Manage packages in the file manager",
        .overviewRefreshEveryTwoSeconds: "Check packages and windows every 2 seconds",
        .overviewRefreshPolicy: "Refresh policy",
        .overviewReinject: "Inject again",
        .overviewResources: "Resource directory",
        .overviewRestartAndConnect: "Start enhanced mode",
        .overviewRestartCodexUI: "Restart the Codex interface",
        .overviewRestartCodexUIDetail: "Save your work and exit the official Codex app normally, then reopen it.",
        .overviewRestartDetail: "Ownership of the official Codex debugging listener has not been verified on this platform. Page enhancement is unavailable; normal Codex launch and local settings remain available.",
        .overviewSubtitle: "Connection status, injection controls, and common actions in one place.",
        .overviewTitle: "Manage local interface enhancements for Codex",
        .overviewViewLogs: "View logs",
        .packagesActiveVersion: "Active v{version}",
        .packagesBuild: "Build",
        .packagesBuilding: "Building…",
        .packagesCannotBuild: "Cannot build",
        .packagesCheckRemoteUpdates: "Check for remote updates",
        .packagesCheckingRemote: "Checking…",
        .packagesChooseDirectory: "Choose package directory",
        .packagesChooseZip: "Choose ZIP file",
        .packagesClearError: "Clear action error",
        .packagesClearMessage: "Clear action message",
        .packagesClearSearch: "Clear search and filters",
        .packagesCollapsed: "Collapsed",
        .packagesDelete: "Delete package",
        .packagesDeleteConfirm: "Delete",
        .packagesDeleteFailed: "Could not delete package {name}: {message}",
        .packagesDeleteHelp: "Delete package source, local build artifacts, and package settings",
        .packagesDeleteMessage: "This permanently deletes the package source, local build artifacts, and package settings. Packages that depend on it may stop working. This action cannot be undone.",
        .packagesDeleteSuccess: "Deleted package {name}.",
        .packagesDeleteTitle: "Delete {name}?",
        .packagesDependencyConstraint: "Dependency constraint",
        .packagesDependencyInstalledSource: "Installed source: {url}",
        .packagesDependencyNoGitSource: "No Git source declared; looking locally only",
        .packagesDependencyOrderFirst: "Dependency order takes precedence",
        .packagesDependencyOriginInstallable: "Installable from Git",
        .packagesDependencyOriginLocal: "Provided locally",
        .packagesDependencyOriginLocalOnly: "Local only",
        .packagesDependencyOriginManaged: "Managed by Git",
        .packagesDependencySelector: "{type}: {value}",
        .packagesDependencyStateBlocked: "Dependency chain blocked",
        .packagesDependencyStateCycle: "Dependency cycle",
        .packagesDependencyStateDisabled: "Disabled",
        .packagesDependencyStateDisabledVersion: "Disabled · v{version}",
        .packagesDependencyStateInvalidRequirement: "Invalid version range",
        .packagesDependencyStateMissingInstallable: "Available from Git",
        .packagesDependencyStateMissingLocal: "Missing locally",
        .packagesDependencyStateNotBuilt: "Not built",
        .packagesDependencyStateNotBuiltVersion: "Not built · v{version}",
        .packagesDependencyStateSatisfied: "OK",
        .packagesDependencyStateSatisfiedVersion: "OK · v{version}",
        .packagesDependencyStateSelfReference: "Depends on itself",
        .packagesDependencyStateSourceConflict: "Source conflict",
        .packagesDependencyStateVersionMismatch: "v{version} does not match",
        .packagesDependencySummaryCritical: "{total} dependencies · {pending} errors",
        .packagesDependencySummaryOK: "Dependencies {total}/{total} OK",
        .packagesDependencySummaryPending: "{total} dependencies · {pending} need attention",
        .packagesDetailActiveBuildError: "v{version} is still running. {message}",
        .packagesDetailCompilerUpdate: "The current artifact was built with esbuild {version}.",
        .packagesDetailDeleting: "Removing package source, local build artifacts, and package settings.",
        .packagesDetailDependencyIssues: "There are {count} dependency issues. Expand the dependency details to see each status.",
        .packagesDetailDependencyUpdate: "The current build is still running. Dependencies or build configuration must be synchronized manually.",
        .packagesDetailExporting: "Preparing the package source as a reinstallable ZIP.",
        .packagesDetailLastBuilt: "Last built: {date}",
        .packagesDetailNodeAuthorizationRequired: "The entire package is blocked. Review the author's description and authorize this version before it can run.",
        .packagesDetailPinnedChanged: "The remote tag or release now points to a different commit. Normal updates are blocked to prevent silent replacement.",
        .packagesDetailRemoteAvailable: "{reference} was updated to {commit}. Select it to download and build.",
        .packagesDetailSourceChanged: "The current build is still running. New source has not been activated.",
        .packagesDetailVersionUpdate: "v{current} is still running. Select to update to v{next}.",
        .packagesDeveloperAllowUnknownNode: "Run unknown Node packages automatically (this session only)",
        .packagesDeveloperAllowUnknownNodeDetail: "Available only in developer mode and always turns off when the app restarts.",
        .packagesDeveloperMode: "Developer mode",
        .packagesDeveloperModeDetail: "Developer mode automatically builds source changes in enabled packages. Dependency and version updates still require confirmation.",
        .packagesEmptyDetail: "Create a package directory with package.json in the packages directory, then rescan.",
        .packagesEmptyTitle: "No packages found",
        .packagesEnableDependencies: "Enable dependencies",
        .packagesEnablePackage: "Enable {name}",
        .packagesEnabledSummary: "{enabled} / {total} enabled, {active} active",
        .packagesExpanded: "Expanded",
        .packagesExportFailed: "Could not export {name}: {message}",
        .packagesExportSuccess: "Exported {name}: {file}",
        .packagesExportZip: "Export as ZIP",
        .packagesExportZipHelp: "Save the package source as a ZIP that can be installed again",
        .packagesExporting: "Exporting {name}…",
        .packagesFilter: "Filter packages",
        .packagesFilterAll: "All",
        .packagesFilterDisabled: "Disabled",
        .packagesFilterEnabled: "Enabled",
        .packagesFilterError: "Errors",
        .packagesFilterPending: "Pending",
        .packagesGitAvailable: "{version} is available",
        .packagesGitChecking: "Checking Git…",
        .packagesGitMissing: "Git was not found. Local packages still work, but remote packages cannot be installed or checked.",
        .packagesInstallAndBuild: "Install and build",
        .packagesInstallDependencies: "Install missing dependencies",
        .packagesInstallFailed: "Could not install the package: {message}",
        .packagesInstallLocal: "Install local package",
        .packagesInstallLocalHelp: "Choose a package directory or ZIP. After validation, it is copied into the local packages directory",
        .packagesInstallRemote: "Install from Git",
        .packagesInstallSuccess: "Installed {name}. New packages remain disabled by default.",
        .packagesInstalling: "Installing…",
        .packagesInstallingLocal: "Safely validating and installing the local package…",
        .packagesLoadOrder: "Load order",
        .packagesLoadOrderDetail: "Dependency topology first; otherwise, a lower priority number loads earlier",
        .packagesNoDescription: "No package description was provided.",
        .packagesNoMatchDetail: "Try another search term or filter.",
        .packagesNoMatchTitle: "No matching packages",
        .packagesNodeAuthorizationAllow: "Allow this version",
        .packagesNodeAuthorizationCancel: "Cancel",
        .packagesNodeAuthorizationReason: "Author's description",
        .packagesNodeAuthorizationTitle: "Allow this package to run Node code?",
        .packagesNodeAuthorizationWarning: "Node code runs as your current user. It can read and change files, access the network, start processes, and may run npm scripts while installing dependencies. Allow it only if you trust the author and the purpose described below.",
        .packagesNodeAutomaticWarning: "When enabled, every active Node package that has not been authorized individually can immediately run local code as your user, with full file, network, process, and npm install-script access. This setting is not saved and turns off when the app restarts.",
        .packagesNodeAutomaticWarningAllow: "Allow for this session",
        .packagesNodeAutomaticWarningTitle: "Run unknown Node packages automatically?",
        .packagesNodeAvailable: "Node.js {version} is available",
        .packagesNodeChecking: "Checking Node.js…",
        .packagesNodeMissing: "Node.js, npm, and npx were not found. Install Node.js and rescan.",
        .packagesNotBuiltDetail: "Build the package before it can be loaded.",
        .packagesOpenDirectory: "Open package in the file manager",
        .packagesOpenProjectPage: "Open the {name} project page",
        .packagesPackageCountSuffix: " and {count} packages",
        .packagesPriority: "Priority",
        .packagesPriorityActual: "Actual load position #{position}. User priority {priority} still orders packages without a dependency path between them.",
        .packagesPriorityAfter: "{name} depends on {dependencies}, so it must load after those packages.",
        .packagesPriorityBefore: "{dependencies} depends on {name}, so this package must load first.",
        .packagesRebuild: "Rebuild",
        .packagesRescan: "Rescan",
        .packagesResetPriority: "Restore package default priority {priority}",
        .packagesSearchPlaceholder: "Search packages",
        .packagesSourceVersion: "Source v{version}",
        .packagesStatusActive: "Active",
        .packagesStatusBuildFailed: "Build failed",
        .packagesStatusBuilding: "Building",
        .packagesStatusCompilerChanged: "Compiler changed",
        .packagesStatusDeleting: "Deleting",
        .packagesStatusDependency: "Dependencies pending",
        .packagesStatusDependencyBlocked: "Blocked by dependency",
        .packagesStatusDependencyChanged: "Dependency or configuration changed",
        .packagesStatusDisabled: "Disabled",
        .packagesStatusExporting: "Exporting",
        .packagesStatusInstallingRemote: "Processing remote package",
        .packagesStatusInvalid: "Invalid configuration",
        .packagesStatusNewVersion: "New version found",
        .packagesStatusNodeAuthorizationRequired: "Node authorization required",
        .packagesStatusNotBuilt: "Not built",
        .packagesStatusPayloadFailed: "Could not read artifact",
        .packagesStatusPending: "Build required",
        .packagesStatusPinnedChanged: "Pinned reference changed",
        .packagesStatusRemoteFailed: "Remote operation failed",
        .packagesStatusRemoteUpdate: "Remote update available",
        .packagesStatusRuntimeFailed: "Runtime failed",
        .packagesStatusSourceChanged: "Source changed",
        .packagesStatusUnavailable: "Unavailable",
        .packagesSubtitle: "Each directory is an independent package. Source changes do not take effect until a successful manual build switches the package atomically.",
        .packagesSyncAndBuild: "Sync and build",
        .packagesTitle: "Manage interface enhancements",
        .packagesUpdateAndBuild: "Update and build",
        .packagesUpdateBuild: "Update build",
        .packagesUpdateToVersion: "Update to v{version}",
        .packagesUserPriority: "User priority for {name}",
        .packagesZipFileType: "ZIP archive",
        .remoteClose: "Close",
        .remoteInstall: "Install",
        .remoteRepository: "Repository URL",
        .remoteRepositoryPlaceholder: "https://github.com/owner/package.git",
        .remoteSelector: "Version selection",
        .remoteSubtitle: "The app resolves the remote reference, pins an exact commit, validates the package in a temporary directory, and then saves immutable source.",
        .remoteTitle: "Install package from Git",
        .remoteValidationDetail: "Installation validates package.json, the API version, SemVer, entry points, package dependencies, and the npm lockfile. New packages remain disabled by default. When Node.js is available, locked dependencies are downloaded and the package is built, but it is not enabled automatically.",
        .runtimeEnhancementUnsupported: "Ownership of the official Codex debugging listener has not been verified on this platform. Page enhancement is unavailable; normal Codex launch and local settings remain available.",
        .runtimeEnhancementUnsupportedTitle: "Page enhancement unavailable",
        .selectorBranch: "Specific branch",
        .selectorBranchDefault: "main",
        .selectorBranchValue: "Branch name",
        .selectorCommit: "Specific commit",
        .selectorCommitValue: "Commit SHA",
        .selectorDefaultBranch: "Default branch",
        .selectorGithubLatestRelease: "Latest GitHub Release",
        .selectorGithubRelease: "Specific GitHub Release",
        .selectorGithubReleaseValue: "Release tag",
        .selectorLatestSemverTag: "Latest SemVer tag",
        .selectorTag: "Specific tag",
        .selectorTagValue: "Tag name",
        .statusCodexNotRunningDetail: "You can open Codex again",
        .statusCodexNotRunningTitle: "Codex is not running",
        .statusConnectedMany: "Connected to {count} windows",
        .statusConnectedOne: "Connected to Codex",
        .statusDisabledTitle: "Interface enhancements are off",
        .statusErrorTitle: "Connection error",
        .statusLaunchingCodexTitle: "Starting Codex",
        .statusRecoveryPendingDetail: "Page cleanup is not fully confirmed. Retry cleanup; close the debug listener by exiting normally and reopening from the official entry point.",
        .statusRecoveryPendingTitle: "Recovery pending",
        .statusRestartRequiredDetail: "Save your work and exit Codex normally before starting enhanced mode. Existing windows remain open.",
        .statusRestartRequiredTitle: "Enhanced connection needs preparation",
        .statusStartingTitle: "Starting",
        .statusWaitingForCDPTitle: "Waiting for the debug port",
        .statusWaitingForPageDetail: "Listener ownership is verified; waiting for the official Codex main page.",
        .statusWaitingForPageTitle: "Waiting for a Codex page",
        .updateApplyProgress: "Downloading and installing the full update…",
        .updateAutoCheck: "Automatically check for updates and ask before downloading and installing a new version",
        .updateAvailable: "Update available",
        .updateChannel: "Update channel",
        .updateChannelBeta: "Beta",
        .updateChannelBetaDetail: "Check stable, Beta, and RC releases",
        .updateChannelStable: "Stable",
        .updateChannelStableDetail: "Check stable releases only",
        .updateCheck: "Check for Updates",
        .updateCheckFailed: "Could not check for updates: {message}",
        .updateCheckFirst: "Check for updates first.",
        .updateChecking: "Checking…",
        .updateCurrent: "Up to date",
        .updateCurrentVersion: "Current version",
        .updateDownload: "Download {version}",
        .updateDownloadProgress: "Downloading update: {progress}%",
        .updateInstall: "Install {version}",
        .updateInstallFailed: "Could not install the update: {message}",
        .updateInstallingProgress: "Download complete. Installing and restarting…",
        .updateLastCheck: "Last checked",
        .updateLater: "Later",
        .updateLatestVersion: "Latest in channel",
        .updateNetworkUnavailable: "The network is currently unavailable.",
        .updateNever: "Never",
        .updateNoRelease: "There is no GitHub Release available in this channel.",
        .updateNoneAvailable: "There is no update to install.",
        .updateNotConfigured: "Application updates are not configured for this build. Use a release published by this project.",
        .updateNotInstalled: "This is a portable build. Install the app with Setup.exe before using automatic updates.",
        .updatePromptMessage: "You have {current}. Version {latest} is available. Download and install it now?",
        .updateRepository: "Project page",
        .updateRestoreReminder: "Restore reminder",
        .updateSkip: "Skip This Version",
        .updateSkipMessage: "Version {version} was skipped. You can still download it manually or restore the reminder.",
        .updateSkipped: "Skipped",
        .updateSoftwareUpdate: "Software Update",
        .updateSubtitle: "Choose an update channel and get the right release for this device from GitHub Releases.",
        .updateTitle: "About & Updates",
        .updateVersionBuild: "Version {version} (Build {build})",
        .updateViewRelease: "View Release",
    ]
    static let contract = BackendPresentationContract(version: 2, locale: "en", languagePreference: "auto", languageOrder: ["auto", "zh-CN", "zh-TW", "en", "ja", "ko"], languageOptions: ["auto": "Automatic (System Language)", "en": "English", "ja": "日本語", "ko": "한국어", "zh-CN": "简体中文", "zh-TW": "繁體中文"], text: Dictionary(uniqueKeysWithValues: text.map { ($0.key.rawValue, $0.value) }), tokens: BackendPresentationTokens(windowMinWidth: 820, windowMinHeight: 560, windowDefaultWidth: 920, windowDefaultHeight: 640, navigationWidth: 220, contentMaxWidth: 1120, pagePadding: 32, sectionSpacing: 28, cardPadding: 20, cardCornerRadius: 14, controlSpacing: 12, compactSpacing: 7, statusIconSize: 36, animationFastMS: 120, animationStandardMS: 220, accentColor: "#0A84FF", successColor: "#30D158", warningColor: "#FF9F0A", dangerColor: "#FF453A"), actions: BackendAvailableActions(openCodex: true, restartCodex: false, restartCodexUI: false, reinject: false, openPackagesDirectory: true, openLogFile: true, openRepository: true, setEnabled: true, setDisableGPUAcceleration: true, setDeveloperMode: true, reloadPackages: true, installLocalPackage: true, installRemotePackage: false, checkNodeEnvironment: true, checkGitEnvironment: true, checkManagedPackageUpdates: false, refreshLog: true, clearLog: false, readAuthoringPrompt: false, checkAppUpdate: false, setUpdatePreferences: false, setLanguage: true, installAppUpdate: false), status: BackendStatusPresentation(title: "Starting", detail: "Codex Tweaks is establishing a local connection.", tone: "accent"), platform: BackendPlatformPresentation(operatingSystem: "darwin", architecture: "universal", cdpEndpoint: "127.0.0.1:9335", repositoryURL: "https://github.com/aloysk/codex-tweaks", updateInstallStrategy: "sparkle"))
}
